### ISSUE TITLE
Security Slam: Kubernetes Lightning Round

### ISSUE THREAD

**Issue by ricardoapl** [kubernetes-sigs/karpenter#876]
### Description

Open tasks for Kubernetes Security Slam 2023

**Release to Community Infrastructure**

Tasks 1 and 2 are not relevant, because images are not part of the release process for Karpenter

- [x] Task 1: Releases are being made via CI (https://github.com/kubernetes-sigs/karpenter/issues/868)
- [x] Task 2: Check that Images are Staged and Promoted Using Community Infra (https://github.com/kubernetes-sigs/karpenter/issues/874)

**Automate Security Documentation**

Task 3 is not relevant, because Karpenter is not a separate distributable artifact

- [x] Task 3: Ensure SBOMs are Generated by Kubernetes BOM (https://github.com/kubernetes-sigs/karpenter/pull/871)
- [x] Task 4: Ensure SLSA Attestations are Generated when Possible (https://github.com/kubernetes-sigs/karpenter/pull/889)
- [x] Task 5: Ensure the Project has a VEX Feed (https://github.com/kubernetes-sigs/karpenter/pull/869 and https://github.com/kubernetes-sigs/karpenter/pull/870)

**CLOMonitor: Secure Development Practices**

- [x] Task 7: Set up CLOMonitor Tracking (https://github.com/cncf/clomonitor/pull/1385)
- [x] Task 8: Check for Binary Artifacts (no binaries found in the repo)
- [x] Task 9: Review the Code Review (all changesets reviewed)
- [x] Task 10: Dangerous Workflow (no dangerous workflow patterns detected)
- [x] Task 11: Security Insights (https://github.com/kubernetes-sigs/karpenter/issues/877 and https://github.com/kubernetes-sigs/karpenter/pull/878)
- [x] Task 12: Dependencies Policy (https://github.com/kubernetes-sigs/karpenter/pull/900)
- [x] Task 13: Dependency update tool (update tool detected, dependabot)
- [x] Task 15: Token Permissions (https://github.com/kubernetes-sigs/karpenter/pull/884)

This checklist was developed by @eddie-knight and @puerco to help guide contributions. When the project tracking kicks in on https://clomonitor.io/projects/cncf/karpenter then more of the security hygiene state will be visible as well.

**Comment by coder12git** [comment]
@ricardoapl we need to update this

**Comment by ricardoapl** [comment]
Thank you @coder12git, should be updated now

Please let me know if I missed something

/cc @YashPimple @sreeram-venkitesh

**Comment by jonathan-innis** [comment]
> Ensure SBOMs are Generated by Kubernetes BOM

How common are SBOMs when you are just shipping a library? I'm familiar with pushing them as part of an image build, but since we aren't building an image here, where would these get stored?

**Comment by ricardoapl** [comment]
> How common are SBOMs when you are just shipping a library? I'm familiar with pushing them as part of an image build, but since we aren't building an image here, where would these get stored?

That's a good point, I'm also not familiar with such use case. Go's `go.sum` already provides a detailed list of direct and transitive dependencies, but maybe generating an SBOM for Karpenter could be useful for supplying clear and accurate information about dependencies (and transitive dependencies) downstream in a consistent format. Perhaps the biggest benefit here might come from including VEX (Vulnerability Exploitability eXchange) information later on to the SBOM for preemptively assessing vulnerabilities and communicating likely false positives downstream. Not really sure where these would get stored though, but perhaps @puerco can help us out here?

**Comment by jonathan-innis** [comment]
> but I think they would be placed in [GitHub Release](https://github.com/kubernetes-sigs/karpenter/releases)

Agree that this is best put next to a Release in the Github Releases tab. I'll wait for @puerco to comment here before we decide what we should do with the SBOM generation.

**Comment by coder12git** [comment]
@ricardoapl task- 11, 12 is also completed.

**Comment by ricardoapl** [comment]
@coder12git I think this project doesn't pass the dependencies policy check yet, maybe we are missing something?

Perhaps the Google Docs for Security Slam: Kubernetes Lightning Round could be useful in figuring out what's missing

**Comment by mlieberman85** [comment]
> > Ensure SBOMs are Generated by Kubernetes BOM
> 
> How common are SBOMs when you are just shipping a library? I'm familiar with pushing them as part of an image build, but since we aren't building an image here, where would these get stored?

Library SBOMs are not particularly useful unless that library is a distributable artifact along with its resolved dependencies.

**Comment by jonathan-innis** [comment]
#889 had referenced this which caused this issue to close by accident

**Comment by coder12git** [comment]
@ricardoapl task-4 done

**Comment by jonathan-innis** [comment]
> Library SBOMs are not particularly useful unless that library is a distributable artifact along with its resolved dependencies

So IIUC, since the library is getting distributed through the go management system and not as a separate artifact, we can close task 3 as completed/not needed?

**Comment by coder12git** [comment]
> So IIUC, since the library is getting distributed through the go management system and not as a separate artifact, we can close task 3 as completed/not needed?

Yes..

**Comment by sreeram-venkitesh** [comment]
With #870 merged, task 5 is also completed 🎉 Huge thanks to @jonathan-innis!

**Comment by ricardoapl** [comment]
> So IIUC, since the library is getting distributed through the go management system and not as a separate artifact, we can close task 3 as completed/not needed?

Yes, let's close Task 3

**Comment by coder12git** [comment]
@ricardoapl task - 12 done

**Comment by coder12git** [comment]
With this, ig we have completed all our tasks, huge thanks to @jonathan-innis for all your reviews 🎉

**Comment by ricardoapl** [comment]
Great! All CLOMonitor Security checks should be passing now, except for SBOM and signed releases (as expected) :rocket:

https://clomonitor.io/projects/cncf/karpenter#karpenter_security

Thank you everyone, I believe we can close this issue now
